const { Keypair, Asset, TransactionBuilder, Operation, Account } = require('@stellar/stellar-sdk');
const rpc = require('@stellar/stellar-sdk').rpc;
const fs = require('fs');

async function main() {
    try {
        const s = new rpc.Server('https://soroban-testnet.stellar.org');
        const testnetData = JSON.parse(fs.readFileSync('../testnet.json', 'utf8'));
        const { alice, bob } = testnetData;

        // Note: You need Alice and Bob's secret keys. In setup.ps1 we generated them.
        // Wait, how do I get the secret keys in JS if they were generated by stellar-cli?
        // Let's just generate NEW keys here, fund them, create the asset, and save to testnet.json!
        
        console.log("Generating new Alice and Bob...");
        const aliceKey = Keypair.random();
        const bobKey = Keypair.random();
        
        console.log("Funding Alice and Bob...");
        await fetch(`https://friendbot.stellar.org?addr=${aliceKey.publicKey()}`);
        await fetch(`https://friendbot.stellar.org?addr=${bobKey.publicKey()}`);

        const aliceAccount = await s.getAccount(aliceKey.publicKey());
        const bobAccount = await s.getAccount(bobKey.publicKey());

        const asset = new Asset('TST', aliceKey.publicKey());

        console.log("Bob adding trustline...");
        let tx = new TransactionBuilder(bobAccount, {fee: '10000', networkPassphrase: 'Test SDF Network ; September 2015'})
            .addOperation(Operation.changeTrust({ asset: asset }))
            .setTimeout(300)
            .build();
        tx.sign(bobKey);
        await s.sendTransaction(tx);

        console.log("Alice minting to Bob...");
        let tx2 = new TransactionBuilder(aliceAccount, {fee: '10000', networkPassphrase: 'Test SDF Network ; September 2015'})
            .addOperation(Operation.payment({ destination: bobKey.publicKey(), asset: asset, amount: '100' }))
            .setTimeout(300)
            .build();
        tx2.sign(aliceKey);
        await s.sendTransaction(tx2);

        testnetData.alice = aliceKey.publicKey();
        testnetData.aliceSecret = aliceKey.secret();
        testnetData.bob = bobKey.publicKey();
        testnetData.bobSecret = bobKey.secret();
        testnetData.tokenId = asset.contractId('Test SDF Network ; September 2015');

        fs.writeFileSync('../testnet.json', JSON.stringify(testnetData, null, 2));
        console.log("Done setup2.js");
    } catch(e) {
        console.error(e);
    }
}
main();
